#!/bin/sh

case "$1" in
	start|restart|reload)
		printf 'Running sysctl: '
		if [ -r /etc/sysctl.conf ]; then
			if /sbin/sysctl -p /etc/sysctl.conf >/dev/null; then
				echo "OK"
			else
				echo "FAIL"
				exit 1
			fi
		else
			echo "OK (no /etc/sysctl.conf)"
		fi
		;;
	stop)
		:
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac
