#!/bin/sh

DAEMON=/usr/sbin/ble-wifi-setup
PIDFILE=/var/run/ble-wifi-setup.pid

case "$1" in
start)
	[ -e /dev/esp-ble ] || exit 0
	printf 'Starting BLE WiFi setup: '
	start-stop-daemon -S -q -m -p "$PIDFILE" -b -x "$DAEMON" && echo "OK" || echo "FAIL"
	;;
stop)
	printf 'Stopping BLE WiFi setup: '
	start-stop-daemon -K -q -p "$PIDFILE"
	rm -f "$PIDFILE"
	echo "OK"
	;;
restart|reload)
	"$0" stop
	sleep 1
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
